spring.application.name=corporateInternetBanking
server.port=1990
spring.datasource.url=jdbc:postgresql://localhost:5432/corporate_internt_banking
spring.datasource.username=root
spring.datasource.password=postgres
spring.datasource.integratedSecurity=true
#spring.jpa.database-platform=org.postgres/Driver\hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
application.security.jwt.secretKey=dGVjaGltb3J0YWxAbW9qb2xhYW5kdGltb3RoeUAyMDI2
application.security.jwt.expiration=36000000
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=adebolamojolaoluwajoy@gmail.com
spring.mail.password=olyz wlil mzor ejup
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=1000
spring.mail.properties.mail.smtp.timeout=1000
spring.mail.properties.mail.smtp.writetimeout=1000
notification.jobs.interval=3600000
//transaction.jobs.intervals=86400000
exchange.rate.base.url=${EXCHANGE_RATE_BASE_URL:https://v6.exchangerate-api.com/v6/0b1d2d0491a30b594d716ea4}
